server:
  port: 8080
  servlet:
    context-parameters:
      defaultHtmlEscape: true
    session:
      timeout: 40m
      cookie:
        http-only: true
      tracking-modes: cookie
  forward-headers-strategy: NATIVE

spring:

  application:
    name: aia

  spring:
    security:
      enabled: false

  aop:
    auto: true
    proxy-target-class: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration

  datasource:
      name: master
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=motcdb;selectMethod=cursor;socketTimeout=30000;encrypt=true;trustServerCertificate=true;validateServerCertificate=false;
      username: sa
      password: asas2826
      hikari:
        pool-name: ManageHikariCP
        auto-commit: true
        maximum-pool-size: 32
        max-lifetime: 1800000
        connection-timeout: 30000
        transaction-isolation: TRANSACTION_READ_COMMITTED

  http:
    encoding:
      force: true

  jta:
    enabled: false

  mvc:
    static-path-pattern: /static/**

  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

openai:
  api:
    key: "sk-63iPahcgh_m5_E0w-mFrgk153YkmtW8569DpDyMOaPT3BlbkFJRv2hWy45FB-TP7Vj-CarzGLbGT32xKNwNOwdNls7AA"
  organizationID: "org-7mQpXE2FKJ1Pfqe0F8Kc3Sja"

line:
  bot:
    channel-token: "9u+LjgMDJ+4dWJxp10y+CkdvVv6hdhnbODnKl1ZQFXnuwLzO75m245iEJS3Wq2VYk9J5WRO5qwUI17kubyyZLZnPY5LYqp8B/hwr67flS5IodO04KmkDNUxk1oGFqrbWAaaWIPbm/1i2n0jsgzak9gdB04t89/1O/w1cDnyilFU="
    channel-secret: "733a19feb92498ca3e890ac9869fed65"
    userId: "Udb7d78437f21b1539430078df9603461"
    handler:
      enabled: true
      path: "/callback"

  login:
    channel:
      channelId: ""
      channel-secret: ""
      callbackUrl: ""

app:
  node:
    id: ${APP_NODE_ID:1}

  mail:
    domain: "motc.gov.tw"

  mailserver: '{
          "mailserver": {
              "server": "smtp.gmail.com",
              "mserverport": "587",
              "msender": "a0919319856@gmail.com",
              "mpass": "npwpquopcbzcydsr",
              "mailsender": "npa",
              "author": "true"

          }
      }'

  config:
    path: "config.yml"

  pebble:
    path: ""

  check:
    apppath: "D:/SystexProject_NCC/bcb16222020005/Frontend/target/classes/templates/module/app/"

  upload:
    path: "D:/SystexProject_NCC/bcb16222020005/Upload/download/"
    temppath: "D:/SystexProject_NCC/bcb16222020005/Upload/download/origin/"
    filepath: "D:/SystexProject_NCC/bcb16222020005/Upload/download/doc/"
    picpath: "D:/SystexProject_NCC/bcb16222020005/Upload/download/pic/"
    mediapath: "D:/SystexProject_NCC/bcb16222020005/Upload/download/media/"
    transpdf: "D:/SystexProject_NCC/bcb16222020005/Upload/download/pdf/"
    menufilepath: "D:/SystexProject_NCC/bcb16222020005/Upload/download/menu/"
    fckfilepath: "D:/SystexProject_NCC/bcb16222020005/Upload/userfiles/file"
    fckpicpath: "D:/SystexProject_NCC/bcb16222020005/Upload/userfiles/image"
